parameters:
  AzureSubscription: ""
  SetEsfaResourceGroupTagsScript: "https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1"
  PackageFile: ""
  ApiPackageFile: ""
  DatabasePackageFile: ""
  ArmTemplateFolder: ""
  Location: "West Europe"
  ArmOutputVariableName: "ARMOutputs"
  EnvironmentTag: "DEV/Test"
  ParentBusiness: ""
  ServiceOffering: ""
  ResourceGroup: ""
  DfCDevopsPath: ""
  EnvironmentName: ""
  AppSharedResourceGroup: ""
  appSharedCosmosDBName: ""
  AppServiceName: ""
  ApiAppServiceName: ""
  SharedResourceGroupName: ""
  ApimServiceName: ""
  ApimProductInstanceName: ""
  ApiName: ""
  ApiId: ""
  APIMPolicyPath: ""
  ApimImportScript: ""
  PSScriptPath: ""
  SpecificationPath: ""
  PageRegistrationPath: ""
  PageRegistrationFile: ""
  AppRegistryApiUrl: ""
  ApimCompositeKey: ""
  
jobs:
  - deployment: DeployTemplate
    displayName: "Deploy arm templates"
    environment: ${{ parameters.EnvironmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../StepTemplates/deploy-arm-template.yml
              parameters:
                AzureSubscription: "${{ parameters.AzureSubscription }}"
                DfCDevopsPath: "${{ parameters.DfCDevopsPath }}"
                SetEsfaResourceGroupTagsScript: "${{ parameters.SetEsfaResourceGroupTagsScript }}"
                EnvironmentTag: "${{ parameters.EnvironmentTag }}"
                ParentBusiness: "${{ parameters.ParentBusiness }}"
                ServiceOffering: "${{ parameters.ServiceOffering }}"
                ResourceGroup: "${{ parameters.ResourceGroup }}"
                Location: "${{ parameters.Location }}"
                ArmOutputVariableName: "${{ parameters.ArmOutputVariableName }}"
                ArmTemplateFolder: "${{ parameters.ArmTemplateFolder }}"
                AppSharedResourceGroup: "${{ parameters.AppSharedResourceGroup }}"
                appSharedCosmosDBName: "${{ parameters.appSharedCosmosDBName }}"
                PSScriptPath: "${{ parameters.PSScriptPath }}"

  - deployment: DeployApplication
    displayName: "Deploy Application"
    environment: ${{ parameters.EnvironmentName }}
    dependsOn:
      - DeployTemplate
    strategy:
      runOnce:
        deploy:
          steps:
            - task: SqlAzureDacpacDeployment@1
              displayName: "Deploy database"
              inputs:
                azureSubscription: '${{ parameters.AzureSubscription }}'
                ServerName: '$(sharedSqlServerFqdn)'
                DatabaseName: 'dfc-$(AzureEnvironmentName)-app-skillscentral-db'
                SqlUsername: '$(sharedSqlServerUsername)'
                SqlPassword: '$(sharedSqlServerPassword)'
                DacpacFile: ${{ parameters.DatabasePackageFile }}
                # This option needs to be uncommented when dropping tables/columns containing data:
                # AdditionalArguments: /p:BlockOnPossibleDataLoss=false

            - template: ../StepTemplates/deploy-azure-app-service-with-apim.yml
              parameters:
                WebAppName: "${{ parameters.AppServiceName }}"
                AzureSubscription: "${{ parameters.AzureSubscription }}"
                DfCDevopsPath: "${{ parameters.DfCDevopsPath }}"
                PackageFile: "${{ parameters.PackageFile }}"
                ResourceGroup: "${{ parameters.ResourceGroup }}"
                SharedResourceGroupName: "${{ parameters.SharedResourceGroupName }}"
                ApimServiceName: "${{ parameters.ApimServiceName }}"
                ApimProductInstanceName: "${{ parameters.ApimProductInstanceName }}"
                ApiName: "${{ parameters.ApiName }}"
                ApiId: "${{ parameters.ApiId }}"
                APIMPolicyPath: "${{ parameters.APIMPolicyPath }}"
                ApimImportScript: "${{ parameters.ApimImportScript }}"
                SpecificationPath: "${{ parameters.SpecificationPath }}"

            - template: ../StepTemplates/deploy-page-registration.yml
              parameters:
                AzureSubscription: "${{ parameters.AzureSubscription }}"
                PageRegistrationPath: "${{ parameters.PageRegistrationPath }}"
                PageRegistrationFile: "${{ parameters.PageRegistrationFile }}"
                AppRegistryApiUrl: "${{ parameters.AppRegistryApiUrl }}"
                ApimCompositeKey: "${{ parameters.ApimCompositeKey }}"

            - template: ../StepTemplates/deploy-azure-api-app-service.yml
              parameters:
                WebAppName: "${{ parameters.ApiAppServiceName }}"
                AzureSubscription: "${{ parameters.AzureSubscription }}"
                DfCDevopsPath: "${{ parameters.DfCDevopsPath }}"
                PackageFile: "${{ parameters.ApiPackageFile }}"
                ResourceGroup: "${{ parameters.ResourceGroup }}"
                SharedResourceGroupName: "${{ parameters.SharedResourceGroupName }}"

