variables:
  - name: ReleaseEnvironmentName
    value: dev
  - name: AppServiceName
    value: $(WebAppPrefix)-as
  - name: ApiAppServiceName
    value: $(ApiAppPrefix)-api-as
  - name: cosmosDBCollectionName
    value: shared-content
  - name: SqlDatabaseName
    value: dfc-dev-app-skillscentral-db
  - name: ResourceGroup
    value: $(WebAppPrefix)-rg
  - name: WebAppProjectName
    value: DFC.App.SkillsHealthCheck
  - name: PageRegistrationFile
    value: registration.json
  - name: ApplicationName
    value: dfc-app-skillshealthcheck
  - name: contentUrl
    value: $(ContentApiAddress)/api/execute
  - name: subscriptionUrl
    value: https://dfc-dev-api-eventgridsubscriptions-fa.$(appServiceDomain)
  - name: SubscriptionSettingsEndpoint
    value: $(ApimProxyAddress)/composite-ui/skillshealthcheck
  - name: apiName
    value: skillshealthcheck
  - name: apiId
    value: composite-ui-skillshealthcheck
  - name: applicationUrl
    value: https://$(AppServiceName).$(appServiceDomain)
  - name: WebAppPrefix
    value: dfc-dev-app-skillshealthcheck
  - name: ApiAppPrefix
    value: dfc-dev-app-skillscentral
  - name: SubscriptionSettingsFilterIncludeEventTypes3
    value:
  - name: SubscriptionSettingsFilterIncludeEventTypes4
    value:
  - name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
    value: /content/sharedcontent/
  - name: EnableAzureMonitorAlerting
    value: true
  - name: aspTier
    value: Standard
  - name: aspInstances
    value: 2
  - name: aspSize
    value: 2
  - name: clientAffinity
    value: false
  - name: appDatabaseThroughput
    value: 400
  - name: ExceptionCountThreshold
    value: 10
  - name: MemoryPercentageThreshold
    value: 75
  - name: CPUPercentageThreshold
    value: 75
  - name: SubscriptionPosturi
    value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
  - name: LoggingLogLevelDefault
    value: Trace
  - name: SessionStateOptionsTtl
    value: 1800