variables:
  - name: ReleaseEnvironmentName
    value: pp
  - name: AppServiceName
    value: $(WebAppPrefix)-as
  - name: cosmosDBCollectionName
    value: shared-content
  - name: ResourceGroup
    value: $(WebAppPrefix)-rg
  - name: WebAppProjectName
    value: DFC.App.SkillsHealthCheck
  - name: PageRegistrationFile
    value: registration.json
  - name: ApplicationName
    value: dfc-app-skillshealthcheck
  - name: contentUrl
    value: $(ContentApiAddress)/api/execute
  - name: subscriptionUrl
    value: https://dfc-pp-api-eventgridsubscriptions-fa.$(appServiceDomain)
  - name: SubscriptionSettingsEndpoint
    value: $(ApimProxyAddress)/composite-ui/skillshealthcheck
  - name: apiName
    value: skillshealthcheck
  - name: apiId
    value: composite-ui-skillshealthcheck
  - name: applicationUrl
    value: https://$(AppServiceName).$(appServiceDomain)
  - name: WebAppPrefix
    value: dfc-pp-app-skillshealthcheck
  - name: SubscriptionSettingsFilterIncludeEventTypes3
    value:
  - name: SubscriptionSettingsFilterIncludeEventTypes4
    value:
  - name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
    value: /content/sharedcontent/
  - name: EnableAzureMonitorAlerting
    value: true
  - name: aspTier
    value: Standard
  - name: aspInstances
    value: 2
  - name: aspSize
    value: 1
  - name: clientAffinity
    value: false
  - name: appDatabaseThroughput
    value: 5000
  - name: ExceptionCountThreshold
    value: 10
  - name: MemoryPercentageThreshold
    value: 75
  - name: CPUPercentageThreshold
    value: 75
  - name: SubscriptionPosturi
    value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
  - name: LoggingLogLevelDefault
    value: Warning
  - name: GovNotifyOptionsAPIKey
    value: findcareerteamwhitelist-a80a0410-bbff-4076-8e27-d7678fd30048-40dca06a-aab0-4e23-b0de-61284715b923
  - name: GovNotifyOptionsEmailTemplateId
    value: 7c5bd660-8d05-4efa-a83a-27de619b195b
  - name: GovNotifyOptionsSmsTemplateId
    value: 769da3de-26a6-4aa9-8662-18f09734ee24
