variables:
  - name: ReleaseEnvironmentName
    value: pp
  - name: AppServiceName
    value: $(WebAppPrefix)-as
  - name: ApiAppServiceName
    value: $(ApiAppPrefix)-api-as
  - name: cosmosDBCollectionName
    value: shared-content
  - name: SqlDatabaseName
    value: dfc-pp-app-skillscentral-db
  - name: ResourceGroup
    value: $(WebAppPrefix)-rg
  - name: WebAppProjectName
    value: DFC.App.SkillsHealthCheck
  - name: PageRegistrationFile
    value: registration.json
  - name: ApplicationName
    value: dfc-app-skillshealthcheck
  - name: contentUrl
    value: $(ContentApiAddress)/api/execute
  - name: subscriptionUrl
    value: https://dfc-pp-api-eventgridsubscriptions-fa.$(appServiceDomain)
  - name: SubscriptionSettingsEndpoint
    value: $(ApimProxyAddress)/composite-ui/skillshealthcheck
  - name: apiName
    value: skillshealthcheck
  - name: apiId
    value: composite-ui-skillshealthcheck
  - name: applicationUrl
    value: https://$(AppServiceName).$(appServiceDomain)
  - name: apiUrl
    value: https://$(ApiAppServiceName).$(appServiceDomain)
  - name: WebAppPrefix
    value: dfc-pp-app-skillshealthcheck
  - name: ApiAppPrefix
    value: dfc-pp-app-skillscentral
  - name: SubscriptionSettingsFilterIncludeEventTypes3
    value:
  - name: SubscriptionSettingsFilterIncludeEventTypes4
    value:
  - name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
    value: /content/sharedcontent/
  - name: EnableAzureMonitorAlerting
    value: true
  - name: appDatabaseThroughput
    value: 5000
  - name: ExceptionCountThreshold
    value: 10
  - name: MemoryPercentageThreshold
    value: 75
  - name: CPUPercentageThreshold
    value: 75
  - name: SubscriptionPosturi
    value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
  - name: LoggingLogLevelDefault
    value: Warning
  - name: SessionStateOptionsTtl
    value: 7200
  - name: ContentMode
    value: PUBLISHED