//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DfE.SkillsCentral.Api.Application.DocumentsFormatters
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Level1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Level1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMS.SkillsCentral.XmlExtensionObjects.SkillsReport.Resources.Level1", typeof(Level1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B,C,E,C,C,D,A,D,B,A,B,E,A,A,E,D.
        /// </summary>
        internal static string AbstractProblems_CorrectAnswers {
            get {
                return ResourceManager.GetString("AbstractProblems_CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,4,10,11,12.
        /// </summary>
        internal static string AbstractProblems_MovementQuestionToCheck {
            get {
                return ResourceManager.GetString("AbstractProblems_MovementQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,8,11,15.
        /// </summary>
        internal static string AbstractProblems_ReflectionQuestionToCheck {
            get {
                return ResourceManager.GetString("AbstractProblems_ReflectionQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7,9,14,15.
        /// </summary>
        internal static string AbstractProblems_RepetitionQuestionToCheck {
            get {
                return ResourceManager.GetString("AbstractProblems_RepetitionQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,3,5,9,13.
        /// </summary>
        internal static string AbstractProblems_RotationQuestionToCheck {
            get {
                return ResourceManager.GetString("AbstractProblems_RotationQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,16,7,1,16,1,6,12,15,16,2,16,2,10,16,1,1,16,9,2,5,12,16,4,16,6,16,1,10,16,16,1,16,5,16,4,10,13,12,16.
        /// </summary>
        internal static string Checking_CorrectAnswers_SetA {
            get {
                return ResourceManager.GetString("Checking_CorrectAnswers_SetA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,C,D,E,F,G,H,I,J,K,A,B,C,D,E,F,G,H,I,J,K,A,B,C,D,E,F,G,H,I,J,K,A,B,C,D,E,F,G,H,I,J,K,A,C,D,E,F,G,H,I,J,K,A,C,D,E,F,G,H,I,J,K,A,C,D,E,F,G,H,I,J,K,A,C,D,E,F,G,H,I,J,K.
        /// </summary>
        internal static string Interest_AnswerClasification {
            get {
                return ResourceManager.GetString("Interest_AnswerClasification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,A little,Moderate,Very High,Extremely High.
        /// </summary>
        internal static string Interest_Band_DisplayNames {
            get {
                return ResourceManager.GetString("Interest_Band_DisplayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at all interested,A little interested,Moderately interested,Very interested,Extremely interested.
        /// </summary>
        internal static string Interest_BandNames {
            get {
                return ResourceManager.GetString("Interest_BandNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely interested,Very interested,Moderately interested.
        /// </summary>
        internal static string Interest_BandNames_ToGetJobFamilies {
            get {
                return ResourceManager.GetString("Interest_BandNames_ToGetJobFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caring,Command and Control,Creative,Data,Engineering,Influencing,Leisure,Organising,Scientific,Storage,Verbal.
        /// </summary>
        internal static string Interest_InternalNames {
            get {
                return ResourceManager.GetString("Interest_InternalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Interest_MaximumScore {
            get {
                return ResourceManager.GetString("Interest_MaximumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caring,Taking Charge,Creative,Number-focused,Engineering,Influencing,Leisure,Organising,Scientific,Storage and Transport,Reading and writing focused.
        /// </summary>
        internal static string Interest_Names {
            get {
                return ResourceManager.GetString("Interest_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Therapies|Education and Training|Medicine and Nursing|Social Services;#Security and Uniformed Services;#Arts, Crafts and Design|Performing Arts, Broadcast and Media;#Financial Services|Information Technology and Information Management;#Construction|Maintenance, Service and Repair|Manufacturing and Engineering;#Marketing, Selling and Advertising|Retail Sales and Customer Service;#Catering Services|Sport, Leisure and Tourism;#Administrative and Clerical|Legal Services|Management and Planning;#Anim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interest_RelatedJobFamilies {
            get {
                return ResourceManager.GetString("Interest_RelatedJobFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13,19,27,34,40.
        /// </summary>
        internal static string Interest_ResultScoring {
            get {
                return ResourceManager.GetString("Interest_ResultScoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAF1DD,D6E3BC,AADD95,599935,1D7911.
        /// </summary>
        internal static string Interest_StrengthOfInterestColors {
            get {
                return ResourceManager.GetString("Interest_StrengthOfInterestColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using social skills to teach, support, care for and help others.;#Working in difficult situations or tough environments, giving clear orders and following commands.;#Using art skills, having new ideas and producing imaginative and original work.;#Working with figures, numbers and data.;#Working step by step to design, build, maintain or repair structures or equipment.;#Working with people and helping change their views and choices.;#Providing a service to people in restaurants, bars, hotels, when they are l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interest_WhatThisInvolves {
            get {
                return ResourceManager.GetString("Interest_WhatThisInvolves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string JobReport_Interests_JobFamiliesToDisplay {
            get {
                return ResourceManager.GetString("JobReport_Interests_JobFamiliesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string JobReport_Skills_JobFamiliesToDisplay {
            get {
                return ResourceManager.GetString("JobReport_Skills_JobFamiliesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string JobReport_SkillsAndInterest_JobFamiliesToDisplay {
            get {
                return ResourceManager.GetString("JobReport_SkillsAndInterest_JobFamiliesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,A,B,A,C,A,C,A,C,C,A.
        /// </summary>
        internal static string Mechanical_CorrectAnswers {
            get {
                return ResourceManager.GetString("Mechanical_CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,4,5.
        /// </summary>
        internal static string Mechanical_MovementOfObjectsQuestionToCheck {
            get {
                return ResourceManager.GetString("Mechanical_MovementOfObjectsQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2,6,8,9.
        /// </summary>
        internal static string Mechanical_PhysicalPrincpleQuestionToCheck {
            get {
                return ResourceManager.GetString("Mechanical_PhysicalPrincpleQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,7,10,11.
        /// </summary>
        internal static string Mechanical_StructureAndWeightQuestionToCheck {
            get {
                return ResourceManager.GetString("Mechanical_StructureAndWeightQuestionToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,C,D,E,F,G,A,B,C,D,E,F,G,A,B,C,D,E,F,G,A,B,C,D,E,F,G,A,B,C,D,E,F,G,A,B,C,D,E,F,G.
        /// </summary>
        internal static string Motivation_Categories {
            get {
                return ResourceManager.GetString("Motivation_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,C,D,E,F,G.
        /// </summary>
        internal static string Motivation_UniqueCategories {
            get {
                return ResourceManager.GetString("Motivation_UniqueCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a social and caring environment, where people get on well together.  They co-operate and help each other.  It is found in caring professions, charities and public services.  It can also be present in some companies, for example in customer service departments..
        /// </summary>
        internal static string MotivationA_Definition {
            get {
                return ResourceManager.GetString("MotivationA_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Focused Environment.
        /// </summary>
        internal static string MotivationA_Name {
            get {
                return ResourceManager.GetString("MotivationA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of environment is structured, predictable and with very clear requirements.  It can be found in areas like administration and book-keeping where the emphasis is on order and high standards..
        /// </summary>
        internal static string MotivationB_Definition {
            get {
                return ResourceManager.GetString("MotivationB_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered Environment.
        /// </summary>
        internal static string MotivationB_Name {
            get {
                return ResourceManager.GetString("MotivationB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of environment is competitive and lively, with an element of risk taking.  People are valued for their ability to press for results and to achieve.  It can often be found in sales roles..
        /// </summary>
        internal static string MotivationC_Definition {
            get {
                return ResourceManager.GetString("MotivationC_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Environment.
        /// </summary>
        internal static string MotivationC_Name {
            get {
                return ResourceManager.GetString("MotivationC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of environment is creative and open to new ways of doing things.  People who value this type of environment are likely to enjoy roles which are free of much of the conventions to do with work, e.g. how you look, how you behave etc..
        /// </summary>
        internal static string MotivationD_Definition {
            get {
                return ResourceManager.GetString("MotivationD_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Environment.
        /// </summary>
        internal static string MotivationD_Name {
            get {
                return ResourceManager.GetString("MotivationD_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This environment values “doers”: people who work hard and who enjoy having something to show for their efforts.  These values tend to be reflected in work that is practical..
        /// </summary>
        internal static string MotivationE_Definition {
            get {
                return ResourceManager.GetString("MotivationE_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive Environment.
        /// </summary>
        internal static string MotivationE_Name {
            get {
                return ResourceManager.GetString("MotivationE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This environment is focused on specialist expertise.  It suggests a role in a technical environment where people gain respect and reward on the basis of their expertise..
        /// </summary>
        internal static string MotivationF_Definition {
            get {
                return ResourceManager.GetString("MotivationF_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist Environment.
        /// </summary>
        internal static string MotivationF_Name {
            get {
                return ResourceManager.GetString("MotivationF_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an environment where the focus is on making money.  Money is also given as a reward for doing well.  It is typically found in commercial businesses rather than public sector or charity work..
        /// </summary>
        internal static string MotivationG_Definition {
            get {
                return ResourceManager.GetString("MotivationG_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Focused Environment.
        /// </summary>
        internal static string MotivationG_Name {
            get {
                return ResourceManager.GetString("MotivationG_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C,B,E,C,E,A,A,C,D,B.
        /// </summary>
        internal static string Numeric_CorrectAnswers_SetA {
            get {
                return ResourceManager.GetString("Numeric_CorrectAnswers_SetA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C,B,E,C,E,A,A,C,D,B.
        /// </summary>
        internal static string Numeric_CorrectAnswers_SetB {
            get {
                return ResourceManager.GetString("Numeric_CorrectAnswers_SetB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1,B1,C1,D1,A2,B2,C2,D2,A3,D3,B3,B1,C1,A1,B2,D1,A2,D2,A3,C2,B3,D3,C1,B1,A1,B2,A2,D1,A3,D2,C2,B3,D3,A1,C1,B1,A2,D1,B2,C2,A3,D2,D3,B3,A1,B1,C1,D1,A2,B2,C2,D2,A3,D3,B3.
        /// </summary>
        internal static string PersonalStyle_Categories {
            get {
                return ResourceManager.GetString("PersonalStyle_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not enjoy persuading others. This means you may have to make an effort to convince potential employers that you have the skills needed to do the job.;#You are likely to be more reserved in groups. This may mean you need to practice being more open in assessment situations.;#;#;#You are less likely to enjoy looking at facts and figures. You may need to challenge yourself to look at data, as such information can be helpful when researching jobs.;#You have a tendency not to try to understand other peop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonalStyle_ChallengeLeft {
            get {
                return ResourceManager.GetString("PersonalStyle_ChallengeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;#;#;#;#;#;#;#;#;#;#.
        /// </summary>
        internal static string PersonalStyle_ChallengeMid {
            get {
                return ResourceManager.GetString("PersonalStyle_ChallengeMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;#You tend to enjoy being around other people and may miss the company of others when looking for work.;#;#;#;#;#;#;#;#;#.
        /// </summary>
        internal static string PersonalStyle_ChallengeRight {
            get {
                return ResourceManager.GetString("PersonalStyle_ChallengeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice talking about your key strengths to a person you know. Ask them to question what you are saying and try to answer their questions.;#Try to talk more and be involved in conversations. Start off by doing this in situations you are more familiar with (for example, with people you know) and then try to do this when looking for work.;#;#;#List the three job options you are most interested in. For each of these find as much information based on facts as you can - for example, from employer websites.;#Whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonalStyle_DevelopmentLeft {
            get {
                return ResourceManager.GetString("PersonalStyle_DevelopmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;#Think about what you can do to find other people also looking for work, for example by going along to your local job centre. Try to find other sociable activities to be involved, for example, volunteering for a local community project.;#;#;#;#;#;#;#;#;#.
        /// </summary>
        internal static string PersonalStyle_DevelopmentRight {
            get {
                return ResourceManager.GetString("PersonalStyle_DevelopmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PersonalStyle_NoOfChallengesToDisplay {
            get {
                return ResourceManager.GetString("PersonalStyle_NoOfChallengesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PersonalStyle_NoOfStrengthsToDisplay {
            get {
                return ResourceManager.GetString("PersonalStyle_NoOfStrengthsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25.
        /// </summary>
        internal static string PersonalStyle_RelaxedTenseScore {
            get {
                return ResourceManager.GetString("PersonalStyle_RelaxedTenseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persuasive,Sociable,Caring,Practical,Data Focused,Behavioural,Innovative,Structured,Tense,Emotionally Controlled,Energetic.
        /// </summary>
        internal static string PersonalStyle_RightNames {
            get {
                return ResourceManager.GetString("PersonalStyle_RightNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;#;#;#;#;#;#;#;#;#;#.
        /// </summary>
        internal static string PersonalStyle_StrengthLeft {
            get {
                return ResourceManager.GetString("PersonalStyle_StrengthLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may enjoy persuading others in some situations. This may help you sell your skills and make a strong impression with potential employers.;#You are likely to enjoy spending time with other people to some extent. This may help you to come across as friendly and sociable in assessment situations.;#;#;#You may enjoy looking at facts and figures. This could help you in researching different types of jobs.;#You may sometimes try to understand other people&apos;s behaviour. This could help you relate well to others [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonalStyle_StrengthMid {
            get {
                return ResourceManager.GetString("PersonalStyle_StrengthMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are likely to enjoy persuading others. This may help you sell your skills and make a strong impression with potential employers.;#You are likely to enjoy spending time with other people. This may help you to come across as friendly and sociable in assessment situations.;#;#;#You are likely to enjoy looking at facts and figures. This may help you in researching different types of jobs.;#Your tendency to try to understand other people&apos;s behaviour may help you relate well to others in interviews.;#Your ope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersonalStyle_StrengthRight {
            get {
                return ResourceManager.GetString("PersonalStyle_StrengthRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5.
        /// </summary>
        internal static string PersonalStyle_TransformedRelaxedTenseScore {
            get {
                return ResourceManager.GetString("PersonalStyle_TransformedRelaxedTenseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1,A2,A3,B1,B2,B3,C1,C2,D1,D2,D3.
        /// </summary>
        internal static string PersonalStyle_UniqueCategories {
            get {
                return ResourceManager.GetString("PersonalStyle_UniqueCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,B,A,C,B,A,C,B,D,E,C,D,E,D.
        /// </summary>
        internal static string Shapes_CorrectAnswers {
            get {
                return ResourceManager.GetString("Shapes_CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT6,CT7,CT8,CT1,CT2,CT3,CT4,CT9,CT5,CT6,CT4,CT1,CT9,CT2,CT7,CT8,CT5,CT3,CT7,CT4,CT3,CT2,CT8,CT6,CT3,CT1,CT9,CT7,CT1,CT8,CT2,CT8,CT4,CT5,CT2,CT6,CT1,CT5,CT7,CT3,CT2,CT5,CT9,CT8,CT6,CT4,CT5,CT6,CT1,CT2,CT4,CT7,CT6,CT2,CT9,CT7,CT5,CT3,CT1,CT8,CT1,CT5,CT6,CT2,CT4,CT9,CT2,CT3,CT8,CT7,CT8,CT5,CT3,CT9,CT6,CT4,CT8,CT3,CT6,CT2,CT7,CT1,CT3,CT9.
        /// </summary>
        internal static string SkillsArea_Categories {
            get {
                return ResourceManager.GetString("SkillsArea_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes responsibility for own actions and for leading others..
        /// </summary>
        internal static string SkillsArea1_Definition {
            get {
                return ResourceManager.GetString("SkillsArea1_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take responsibility for your own actions, take control of situations and lead others..
        /// </summary>
        internal static string SkillsArea1_Description {
            get {
                return ResourceManager.GetString("SkillsArea1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think of a time when you took responsibility for getting something done. Look at what went well and make a point of taking responsibility more often..
        /// </summary>
        internal static string SkillsArea1_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea1_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next time you are in a situation which is unclear, be open about what you think. Clearly explain what you think should be done and why. Explain what you would like other people to do..
        /// </summary>
        internal static string SkillsArea1_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea1_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking Responsibility.
        /// </summary>
        internal static string SkillsArea1_Name {
            get {
                return ResourceManager.GetString("SkillsArea1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00306A1D&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea1_Strength {
            get {
                return ResourceManager.GetString("SkillsArea1_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works well with people by listening, understanding and helping others..
        /// </summary>
        internal static string SkillsArea2_Definition {
            get {
                return ResourceManager.GetString("SkillsArea2_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work well with people, by listening, understanding and helping others..
        /// </summary>
        internal static string SkillsArea2_Description {
            get {
                return ResourceManager.GetString("SkillsArea2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take time to notice when others have too much to do. Talk to them and offer to help them with some of their tasks..
        /// </summary>
        internal static string SkillsArea2_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea2_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think more carefully about those around you. Speak less and listen more. Find out about their lives and issues. Put yourself in their shoes, imagine how they see themselves and how they see you..
        /// </summary>
        internal static string SkillsArea2_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea2_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working with Others.
        /// </summary>
        internal static string SkillsArea2_Name {
            get {
                return ResourceManager.GetString("SkillsArea2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;006B3FD4&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;240&quot; /&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea2_Strength {
            get {
                return ResourceManager.GetString("SkillsArea2_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convinces others and deals well with conflict. Expresses self clearly when speaking and writing..
        /// </summary>
        internal static string SkillsArea3_Definition {
            get {
                return ResourceManager.GetString("SkillsArea3_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convince others, deal with conflict between people and express yourself clearly when speaking and writing..
        /// </summary>
        internal static string SkillsArea3_Description {
            get {
                return ResourceManager.GetString("SkillsArea3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When speaking with others, think about what other people are interested in as well as what you want to say. Use eye contact and positive body language to make others feel comfortable. Gather information to support your point of view. Speak slowly and clearly, to help others understand you..
        /// </summary>
        internal static string SkillsArea3_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea3_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a disagreement starts, try to put yourself in the other person’s shoes before defending your point of view. Look at the disagreement as a difference of ideas or style, rather than of people. Try not to take sides and encourage others to do the same..
        /// </summary>
        internal static string SkillsArea3_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea3_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convincing and Communicating.
        /// </summary>
        internal static string SkillsArea3_Name {
            get {
                return ResourceManager.GetString("SkillsArea3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00181DD8&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea3_Strength {
            get {
                return ResourceManager.GetString("SkillsArea3_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spots problems and gathers information, making judgements based on facts..
        /// </summary>
        internal static string SkillsArea4_Definition {
            get {
                return ResourceManager.GetString("SkillsArea4_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spot problems, gather information and make judgements based on facts..
        /// </summary>
        internal static string SkillsArea4_Description {
            get {
                return ResourceManager.GetString("SkillsArea4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think of a problem you have come across. Write down everything you know about the problem. Now look at what you have written down. Look for similarities. Can you group what you have written down? Are there any areas where you would benefit from having more information? Share this list with someone you trust..
        /// </summary>
        internal static string SkillsArea4_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea4_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look back at some information that you collected to support a decision. Review this information, trying to pick it apart. Is the source trustworthy? Are there an gaps in this information? Is there anything in this information that you think could be wrong? Does this information cover different points of view?.
        /// </summary>
        internal static string SkillsArea4_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea4_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solving Problems .
        /// </summary>
        internal static string SkillsArea4_Name {
            get {
                return ResourceManager.GetString("SkillsArea4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00115AB6&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea4_Strength {
            get {
                return ResourceManager.GetString("SkillsArea4_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comes up with new ideas and different ways for approaching issues..
        /// </summary>
        internal static string SkillsArea5_Definition {
            get {
                return ResourceManager.GetString("SkillsArea5_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to come up with new ideas and different ways for approaching issues..
        /// </summary>
        internal static string SkillsArea5_Description {
            get {
                return ResourceManager.GetString("SkillsArea5_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are next faced with an issue, list all the different ways in which this could be solved. Think of as many different ways as possible, try to fill a whole sheet of paper. Be creative and write all your ideas down. Try not to think about whether your ideas are good or bad, just come up with as many different ideas as possible. Once you have a long list, look back over it. Which of your ideas are similar? Which are different?.
        /// </summary>
        internal static string SkillsArea5_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea5_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out new ways of doing things to see if you can find better ways for getting things done. Think of something that could be done better or improved. Rather than writing down your ideas, draw them. Draw how things are done now and draw how things could be done differently..
        /// </summary>
        internal static string SkillsArea5_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea5_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Thinking.
        /// </summary>
        internal static string SkillsArea5_Name {
            get {
                return ResourceManager.GetString("SkillsArea5_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00C836AA&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///      &lt;w:t&gt;Thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea5_Strength {
            get {
                return ResourceManager.GetString("SkillsArea5_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans own tasks and uses time effectively to produce high quality work..
        /// </summary>
        internal static string SkillsArea6_Definition {
            get {
                return ResourceManager.GetString("SkillsArea6_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan and manage your own time, use your time effectively, focus on detail and produce high quality work..
        /// </summary>
        internal static string SkillsArea6_Description {
            get {
                return ResourceManager.GetString("SkillsArea6_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lists and reminders to make sure you know what needs to get done. Keep a diary one week and see what you complete in that time and what gets put off. Set yourself doable daily tasks and stick to them..
        /// </summary>
        internal static string SkillsArea6_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea6_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next time you are given a task to complete, leave some time at the end to check your work. Look back at your work: are there any mistakes, how can you make it better? Ask others for their advice and suggestions about how they check their own work..
        /// </summary>
        internal static string SkillsArea6_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea6_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning and Focusing on Detail.
        /// </summary>
        internal static string SkillsArea6_Name {
            get {
                return ResourceManager.GetString("SkillsArea6_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00C27B4A&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea6_Strength {
            get {
                return ResourceManager.GetString("SkillsArea6_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapts to changes, remains calm and reacts positively to challenges..
        /// </summary>
        internal static string SkillsArea7_Definition {
            get {
                return ResourceManager.GetString("SkillsArea7_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapt to changes, remain calm under pressure and react positively to challenges..
        /// </summary>
        internal static string SkillsArea7_Description {
            get {
                return ResourceManager.GetString("SkillsArea7_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to work out what causes you stress - think about situations recently where you felt stressed, what you were thinking and what you did. Think about what did and did not help. Think about what you can do next time to make the situation easier to handle..
        /// </summary>
        internal static string SkillsArea7_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea7_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think about the good things that can come out of a changing situation. Think about how new experiences can give you new knowledge and understanding. Treat new challenges as exciting situations..
        /// </summary>
        internal static string SkillsArea7_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea7_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Change and Pressure.
        /// </summary>
        internal static string SkillsArea7_Name {
            get {
                return ResourceManager.GetString("SkillsArea7_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;006E7E74&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea7_Strength {
            get {
                return ResourceManager.GetString("SkillsArea7_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows energy and enthusiasm for meeting difficult goals and taking on new tasks..
        /// </summary>
        internal static string SkillsArea8_Definition {
            get {
                return ResourceManager.GetString("SkillsArea8_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show energy and enthusiasm, work hard to meet difficult tasks and be keen to take on new tasks..
        /// </summary>
        internal static string SkillsArea8_Description {
            get {
                return ResourceManager.GetString("SkillsArea8_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are next asked to do something for someone else, show them that you are excited to help. When you finish the task, ask them if there is anything else you can help with..
        /// </summary>
        internal static string SkillsArea8_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea8_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next time you are given a task to do that you have never done before agree to do it. Think through what you need to do. Talk to other people who have done this before. Work hard to complete the task..
        /// </summary>
        internal static string SkillsArea8_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea8_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Energy and Drive.
        /// </summary>
        internal static string SkillsArea8_Name {
            get {
                return ResourceManager.GetString("SkillsArea8_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;000E6422&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea8_Strength {
            get {
                return ResourceManager.GetString("SkillsArea8_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily learns new information and quickly learns how to use new technologies..
        /// </summary>
        internal static string SkillsArea9_Definition {
            get {
                return ResourceManager.GetString("SkillsArea9_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn new information easily and learn how to use new technologies quickly..
        /// </summary>
        internal static string SkillsArea9_Description {
            get {
                return ResourceManager.GetString("SkillsArea9_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out what different things a computer can help you to do by using tutorials or setting yourself exercises that broaden your knowledge. Seek tips from others with more experience..
        /// </summary>
        internal static string SkillsArea9_DevelopmentTip1 {
            get {
                return ResourceManager.GetString("SkillsArea9_DevelopmentTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think of a topic you are interested in but know little about. Use a computer to find out as much information as you can. Then ask a friend to test your knowledge on this topic..
        /// </summary>
        internal static string SkillsArea9_DevelopmentTip2 {
            get {
                return ResourceManager.GetString("SkillsArea9_DevelopmentTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning and Technology.
        /// </summary>
        internal static string SkillsArea9_Name {
            get {
                return ResourceManager.GetString("SkillsArea9_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:p w:rsidRPr=&quot;00FF6F76&quot; w:rsidR=&quot;003325B3&quot; w:rsidP=&quot;00C836AA&quot; w:rsidRDefault=&quot;003325B3&quot;&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;24&quot; /&gt;
        ///      &lt;/w:rPr&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r w:rsidRPr=&quot;00FF6F76&quot;&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:ascii=&quot;Verdana&quot; w:hAnsi=&quot;Verdana&quot; /&gt;
        ///        &lt;w:color w:val=&quot;000000&quot; /&gt;
        ///        &lt;w:sz w:val=&quot;24&quot; /&gt;
        ///        &lt;w:szCs w:val=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillsArea9_Strength {
            get {
                return ResourceManager.GetString("SkillsArea9_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,A,B,A,C,A,B,C,B,B,C,B,C,C,A,A,A,A,C,C.
        /// </summary>
        internal static string Verbal_CorrectAnswers_SetA {
            get {
                return ResourceManager.GetString("Verbal_CorrectAnswers_SetA", resourceCulture);
            }
        }
    }
}
