//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsDocumentsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocument", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class SkillsDocument : object
    {
        
        private long DocumentIdField;
        
        private string SkillsDocumentTypeField;
        
        private System.DateTime CreatedAtField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private string UpdatedByField;
        
        private System.Nullable<System.DateTime> DeletedAtField;
        
        private string DeletedByField;
        
        private System.Nullable<System.TimeSpan> ExpiresTimespanField;
        
        private SkillsDocumentsService.SkillsDocumentExpiryEnum ExpiresTypeField;
        
        private System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentDataValue> DataValuesField;
        
        private System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentIdentifier> IdentifiersField;
        
        private string SkillsDocumentTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SkillsDocumentType
        {
            get
            {
                return this.SkillsDocumentTypeField;
            }
            set
            {
                this.SkillsDocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UpdatedBy
        {
            get
            {
                return this.UpdatedByField;
            }
            set
            {
                this.UpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> DeletedAt
        {
            get
            {
                return this.DeletedAtField;
            }
            set
            {
                this.DeletedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DeletedBy
        {
            get
            {
                return this.DeletedByField;
            }
            set
            {
                this.DeletedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.TimeSpan> ExpiresTimespan
        {
            get
            {
                return this.ExpiresTimespanField;
            }
            set
            {
                this.ExpiresTimespanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public SkillsDocumentsService.SkillsDocumentExpiryEnum ExpiresType
        {
            get
            {
                return this.ExpiresTypeField;
            }
            set
            {
                this.ExpiresTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentDataValue> DataValues
        {
            get
            {
                return this.DataValuesField;
            }
            set
            {
                this.DataValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentIdentifier> Identifiers
        {
            get
            {
                return this.IdentifiersField;
            }
            set
            {
                this.IdentifiersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string SkillsDocumentTitle
        {
            get
            {
                return this.SkillsDocumentTitleField;
            }
            set
            {
                this.SkillsDocumentTitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocumentExpiryEnum", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public enum SkillsDocumentExpiryEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Logical = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Physical = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocumentDataValue", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class SkillsDocumentDataValue : object
    {
        
        private string TitleField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocumentIdentifier", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class SkillsDocumentIdentifier : object
    {
        
        private string ServiceNameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormatDocumentResponse", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class FormatDocumentResponse : object
    {
        
        private long DocumentIdField;
        
        private string FormatterNameField;
        
        private SkillsDocumentsService.FormatDocumentStatusEnum StatusField;
        
        private System.DateTime CreatedAtDateField;
        
        private string CreatedByField;
        
        private System.Nullable<System.DateTime> UpdatedAtDateField;
        
        private string UpdatedByField;
        
        private System.Nullable<System.DateTime> LastViewDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FormatterName
        {
            get
            {
                return this.FormatterNameField;
            }
            set
            {
                this.FormatterNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SkillsDocumentsService.FormatDocumentStatusEnum Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreatedAtDate
        {
            get
            {
                return this.CreatedAtDateField;
            }
            set
            {
                this.CreatedAtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> UpdatedAtDate
        {
            get
            {
                return this.UpdatedAtDateField;
            }
            set
            {
                this.UpdatedAtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UpdatedBy
        {
            get
            {
                return this.UpdatedByField;
            }
            set
            {
                this.UpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> LastViewDate
        {
            get
            {
                return this.LastViewDateField;
            }
            set
            {
                this.LastViewDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormatDocumentStatusEnum", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public enum FormatDocumentStatusEnum : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Creating = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocumentType", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class SkillsDocumentType : object
    {
        
        private int SysIdField;
        
        private string DocumentTypeTextField;
        
        private System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentTypeDataKey> RequiredKeysField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysId
        {
            get
            {
                return this.SysIdField;
            }
            set
            {
                this.SysIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DocumentTypeText
        {
            get
            {
                return this.DocumentTypeTextField;
            }
            set
            {
                this.DocumentTypeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Collections.Generic.List<SkillsDocumentsService.SkillsDocumentTypeDataKey> RequiredKeys
        {
            get
            {
                return this.RequiredKeysField;
            }
            set
            {
                this.RequiredKeysField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SkillsDocumentTypeDataKey", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class SkillsDocumentTypeDataKey : object
    {
        
        private int DataKeySysIdField;
        
        private string KeyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DataKeySysId
        {
            get
            {
                return this.DataKeySysIdField;
            }
            set
            {
                this.DataKeySysIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyName
        {
            get
            {
                return this.KeyNameField;
            }
            set
            {
                this.KeyNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssessmentType", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public enum AssessmentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abstract = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Checking = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interests = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mechanical = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Motivation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Numerical = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personal = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SkillAreas = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spatial = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verbal = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Level", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public enum Level : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Level3 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accessibility", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public enum Accessibility : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Full = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accessible = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class Question : object
    {
        
        private string AssessmentTitleField;
        
        private SkillsDocumentsService.AssessmentType AssessmentTypeField;
        
        private SkillsDocumentsService.Accessibility AccessibilityField;
        
        private SkillsDocumentsService.Level LevelField;
        
        private string QuestionTitleField;
        
        private string QuestionTextField;
        
        private int QuestionNumberField;
        
        private int TotalQuestionNumberField;
        
        private System.Collections.Generic.List<string> AnswerHeadingsField;
        
        private System.Collections.Generic.List<SkillsDocumentsService.Answer> PossibleResponsesField;
        
        private int QuestionIdField;
        
        private int AssessmentIdField;
        
        private string ImageTitleField;
        
        private string ImageUrlField;
        
        private string ImageCaptionField;
        
        private string QuestionDataField;
        
        private string SubTitleField;
        
        private string IntroductionTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssessmentTitle
        {
            get
            {
                return this.AssessmentTitleField;
            }
            set
            {
                this.AssessmentTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsDocumentsService.AssessmentType AssessmentType
        {
            get
            {
                return this.AssessmentTypeField;
            }
            set
            {
                this.AssessmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public SkillsDocumentsService.Accessibility Accessibility
        {
            get
            {
                return this.AccessibilityField;
            }
            set
            {
                this.AccessibilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public SkillsDocumentsService.Level Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string QuestionTitle
        {
            get
            {
                return this.QuestionTitleField;
            }
            set
            {
                this.QuestionTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string QuestionText
        {
            get
            {
                return this.QuestionTextField;
            }
            set
            {
                this.QuestionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int QuestionNumber
        {
            get
            {
                return this.QuestionNumberField;
            }
            set
            {
                this.QuestionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalQuestionNumber
        {
            get
            {
                return this.TotalQuestionNumberField;
            }
            set
            {
                this.TotalQuestionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Collections.Generic.List<string> AnswerHeadings
        {
            get
            {
                return this.AnswerHeadingsField;
            }
            set
            {
                this.AnswerHeadingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Collections.Generic.List<SkillsDocumentsService.Answer> PossibleResponses
        {
            get
            {
                return this.PossibleResponsesField;
            }
            set
            {
                this.PossibleResponsesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int QuestionId
        {
            get
            {
                return this.QuestionIdField;
            }
            set
            {
                this.QuestionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int AssessmentId
        {
            get
            {
                return this.AssessmentIdField;
            }
            set
            {
                this.AssessmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string ImageTitle
        {
            get
            {
                return this.ImageTitleField;
            }
            set
            {
                this.ImageTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ImageCaption
        {
            get
            {
                return this.ImageCaptionField;
            }
            set
            {
                this.ImageCaptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string QuestionData
        {
            get
            {
                return this.QuestionDataField;
            }
            set
            {
                this.QuestionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string SubTitle
        {
            get
            {
                return this.SubTitleField;
            }
            set
            {
                this.SubTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string IntroductionText
        {
            get
            {
                return this.IntroductionTextField;
            }
            set
            {
                this.IntroductionTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/Entities")]
    public partial class Answer : object
    {
        
        private string ValueField;
        
        private string TextField;
        
        private string ImageSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ImageSource
        {
            get
            {
                return this.ImageSourceField;
            }
            set
            {
                this.ImageSourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0", ConfigurationName="SkillsDocumentsService.ISkillsCentralService")]
    public interface ISkillsCentralService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypes", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypeFields", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypeFieldsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListTypeFieldsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListTypeFieldsAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListFormatters", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListFormattersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListFormattersStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListFormattersAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListServiceIdentifiers", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListServiceIdentifiersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListServiceIdentifiersStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListServiceIdentifiersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListSkillsDocumentTypes", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListSkillsDocumentTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ListSkillsDocumentTypesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListSkillsDocumentTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentWithAuditAsync(long id, string accessedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValues", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValuesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValuesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentDataValuesAsync(long id, System.Collections.Generic.List<string> dataValuesToSelect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValuesWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValuesWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentDataValuesWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentDataValuesWithAuditAsync(long id, System.Collections.Generic.List<string> dataValuesToSelect, string accessedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMeta", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMetaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMetaStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentMetaAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMetaWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMetaWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentMetaWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentMetaWithAuditAsync(long id, string accessedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentType", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypeStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> ReadSkillsDocumentsByDocumentTypeAsync(string documentType, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypePager", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypePagerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypePagerStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> ReadSkillsDocumentsByDocumentTypePagerAsync(string documentType, int page, int pageSize, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypeCount", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypeCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadSkillsDocumentsByDocumentTypeCountStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<long> ReadSkillsDocumentsByDocumentTypeCountAsync(string documentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentsByServiceNameKeyValueAndDocTypeCount", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentsByServiceNameKeyValueAndDocTypeCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/ReadDocumentsByServiceNameKeyValueAndDocTypeCountStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<long> ReadDocumentsByServiceNameKeyValueAndDocTypeCountAsync(string docType, string serviceName, string identifierValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/CreateDefaultDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/CreateDefaultDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/CreateDefaultDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> CreateDefaultDocumentAsync(string docType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<long> InsertDocumentAsync(SkillsDocumentsService.SkillsDocument doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<long> InsertDocumentWithAuditAsync(SkillsDocumentsService.SkillsDocument doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task UpdateDocumentAsync(SkillsDocumentsService.SkillsDocument doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task UpdateDocumentWithAuditAsync(SkillsDocumentsService.SkillsDocument doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValues", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValuesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValuesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task UpdateSkillsDocumentDataValuesAsync(long docId, SkillsDocumentsService.SkillsDocument dataValuesDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValuesWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValuesWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentDataValuesWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task UpdateSkillsDocumentDataValuesWithAuditAsync(long docId, SkillsDocumentsService.SkillsDocument dataValuesDoc, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task LogicalDeleteDocumentAsync(long id, string deletedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/LogicalDeleteDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task LogicalDeleteDocumentWithAuditAsync(long id, string deletedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task DeleteDocumentAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task DeleteDocumentWithAuditAsync(long id, string deletedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocument", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocumentStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task RestoreDocumentAsync(long id, string restoredBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocumentWithAudit", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocumentWithAuditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/RestoreDocumentWithAuditStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task RestoreDocumentWithAuditAsync(long id, string restoredBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentTypeIdsByServiceNameKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentTypeIdsByServiceNameKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentTypeIdsByServiceNameKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<long>> FindDocumentTypeIdsByServiceNameKeyValueAsync(string serviceName, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentIdsByServiceNameKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentIdsByServiceNameKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentIdsByServiceNameKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<long>> FindDocumentIdsByServiceNameKeyValueAsync(string serviceName, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentByKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentByKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentByKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> FindDocumentByKeyValueAsync(string keyValue, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAsync(string serviceName, string id, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocType", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocTypeStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAndDocTypeAsync(string docType, string serviceName, string id, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValuePager", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValuePagerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValuePagerStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValuePagerAsync(string serviceName, string id, int page, int pageSize, string sortBy, string sortDirection, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocTypePager", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocTypePagerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FindDocumentsByServiceNameKeyValueAndDocTypePagerStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAndDocTypePagerAsync(string docType, string serviceName, string id, int page, int pageSize, string sortBy, string sortDirection, bool incData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentMakeRequest", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentMakeRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentMakeRequestStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.FormatDocumentResponse> FormatDocumentMakeRequestAsync(long docId, string formatter, string requestedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentPollStatus", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentPollStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentPollStatusStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.FormatDocumentResponse> FormatDocumentPollStatusAsync(long docId, string formatter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentGetPayload", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentGetPayloadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/FormatDocumentGetPayloadStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<byte[]> FormatDocumentGetPayloadAsync(long docId, string formatter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsDocumentKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsDocumentKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsDocumentKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<string> GetSkillsDocumentKeyValueAsync(long docId, string keyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentKeyValue", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentKeyValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateSkillsDocumentKeyValueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task UpdateSkillsDocumentKeyValueAsync(long docId, string keyName, string keyValue, string updatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentType", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/InsertDocumentTypeStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<string> InsertDocumentTypeAsync(SkillsDocumentsService.SkillsDocumentType docType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentType", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/DeleteDocumentTypeStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task DeleteDocumentTypeAsync(string docTypeText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentType", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/UpdateDocumentTypeStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<string> UpdateDocumentTypeAsync(SkillsDocumentsService.SkillsDocumentType docType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeByName", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeByNameStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocumentType> GetDocumentTypeByNameAsync(string docTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeById", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetDocumentTypeByIdStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocumentType> GetDocumentTypeByIdAsync(int docTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsHealthCheckQuestions", ReplyAction="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsHealthCheckQuestionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://schemas.skillsfundingagency.bis.gov.uk/alse/skillscentral/1.0/ISkillsCentr" +
            "alService/GetSkillsHealthCheckQuestionsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Threading.Tasks.Task<SkillsDocumentsService.Question> GetSkillsHealthCheckQuestionsAsync(SkillsDocumentsService.AssessmentType assessmentType, int questionNumber, SkillsDocumentsService.Level level, SkillsDocumentsService.Accessibility accessibility);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ISkillsCentralServiceChannel : SkillsDocumentsService.ISkillsCentralService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SkillsCentralServiceClient : System.ServiceModel.ClientBase<SkillsDocumentsService.ISkillsCentralService>, SkillsDocumentsService.ISkillsCentralService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SkillsCentralServiceClient() : 
                base(SkillsCentralServiceClient.GetDefaultBinding(), SkillsCentralServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SkillsCentralServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SkillsCentralServiceClient.GetBindingForEndpoint(endpointConfiguration), SkillsCentralServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SkillsCentralServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SkillsCentralServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SkillsCentralServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SkillsCentralServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SkillsCentralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListTypesAsync()
        {
            return base.Channel.ListTypesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListTypeFieldsAsync(string type)
        {
            return base.Channel.ListTypeFieldsAsync(type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListFormattersAsync(string type)
        {
            return base.Channel.ListFormattersAsync(type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListServiceIdentifiersAsync()
        {
            return base.Channel.ListServiceIdentifiersAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> ListSkillsDocumentTypesAsync()
        {
            return base.Channel.ListSkillsDocumentTypesAsync();
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentAsync(long id)
        {
            return base.Channel.ReadDocumentAsync(id);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentWithAuditAsync(long id, string accessedBy)
        {
            return base.Channel.ReadDocumentWithAuditAsync(id, accessedBy);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentDataValuesAsync(long id, System.Collections.Generic.List<string> dataValuesToSelect)
        {
            return base.Channel.ReadDocumentDataValuesAsync(id, dataValuesToSelect);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentDataValuesWithAuditAsync(long id, System.Collections.Generic.List<string> dataValuesToSelect, string accessedBy)
        {
            return base.Channel.ReadDocumentDataValuesWithAuditAsync(id, dataValuesToSelect, accessedBy);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentMetaAsync(long id)
        {
            return base.Channel.ReadDocumentMetaAsync(id);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> ReadDocumentMetaWithAuditAsync(long id, string accessedBy)
        {
            return base.Channel.ReadDocumentMetaWithAuditAsync(id, accessedBy);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> ReadSkillsDocumentsByDocumentTypeAsync(string documentType, bool incData)
        {
            return base.Channel.ReadSkillsDocumentsByDocumentTypeAsync(documentType, incData);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> ReadSkillsDocumentsByDocumentTypePagerAsync(string documentType, int page, int pageSize, bool incData)
        {
            return base.Channel.ReadSkillsDocumentsByDocumentTypePagerAsync(documentType, page, pageSize, incData);
        }
        
        public System.Threading.Tasks.Task<long> ReadSkillsDocumentsByDocumentTypeCountAsync(string documentType)
        {
            return base.Channel.ReadSkillsDocumentsByDocumentTypeCountAsync(documentType);
        }
        
        public System.Threading.Tasks.Task<long> ReadDocumentsByServiceNameKeyValueAndDocTypeCountAsync(string docType, string serviceName, string identifierValue)
        {
            return base.Channel.ReadDocumentsByServiceNameKeyValueAndDocTypeCountAsync(docType, serviceName, identifierValue);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> CreateDefaultDocumentAsync(string docType)
        {
            return base.Channel.CreateDefaultDocumentAsync(docType);
        }
        
        public System.Threading.Tasks.Task<long> InsertDocumentAsync(SkillsDocumentsService.SkillsDocument doc)
        {
            return base.Channel.InsertDocumentAsync(doc);
        }
        
        public System.Threading.Tasks.Task<long> InsertDocumentWithAuditAsync(SkillsDocumentsService.SkillsDocument doc)
        {
            return base.Channel.InsertDocumentWithAuditAsync(doc);
        }
        
        public System.Threading.Tasks.Task UpdateDocumentAsync(SkillsDocumentsService.SkillsDocument doc)
        {
            return base.Channel.UpdateDocumentAsync(doc);
        }
        
        public System.Threading.Tasks.Task UpdateDocumentWithAuditAsync(SkillsDocumentsService.SkillsDocument doc)
        {
            return base.Channel.UpdateDocumentWithAuditAsync(doc);
        }
        
        public System.Threading.Tasks.Task UpdateSkillsDocumentDataValuesAsync(long docId, SkillsDocumentsService.SkillsDocument dataValuesDoc)
        {
            return base.Channel.UpdateSkillsDocumentDataValuesAsync(docId, dataValuesDoc);
        }
        
        public System.Threading.Tasks.Task UpdateSkillsDocumentDataValuesWithAuditAsync(long docId, SkillsDocumentsService.SkillsDocument dataValuesDoc, string updatedBy)
        {
            return base.Channel.UpdateSkillsDocumentDataValuesWithAuditAsync(docId, dataValuesDoc, updatedBy);
        }
        
        public System.Threading.Tasks.Task LogicalDeleteDocumentAsync(long id, string deletedBy)
        {
            return base.Channel.LogicalDeleteDocumentAsync(id, deletedBy);
        }
        
        public System.Threading.Tasks.Task LogicalDeleteDocumentWithAuditAsync(long id, string deletedBy)
        {
            return base.Channel.LogicalDeleteDocumentWithAuditAsync(id, deletedBy);
        }
        
        public System.Threading.Tasks.Task DeleteDocumentAsync(long id)
        {
            return base.Channel.DeleteDocumentAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteDocumentWithAuditAsync(long id, string deletedBy)
        {
            return base.Channel.DeleteDocumentWithAuditAsync(id, deletedBy);
        }
        
        public System.Threading.Tasks.Task RestoreDocumentAsync(long id, string restoredBy)
        {
            return base.Channel.RestoreDocumentAsync(id, restoredBy);
        }
        
        public System.Threading.Tasks.Task RestoreDocumentWithAuditAsync(long id, string restoredBy)
        {
            return base.Channel.RestoreDocumentWithAuditAsync(id, restoredBy);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<long>> FindDocumentTypeIdsByServiceNameKeyValueAsync(string serviceName, string id)
        {
            return base.Channel.FindDocumentTypeIdsByServiceNameKeyValueAsync(serviceName, id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<long>> FindDocumentIdsByServiceNameKeyValueAsync(string serviceName, string id)
        {
            return base.Channel.FindDocumentIdsByServiceNameKeyValueAsync(serviceName, id);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocument> FindDocumentByKeyValueAsync(string keyValue, bool incData)
        {
            return base.Channel.FindDocumentByKeyValueAsync(keyValue, incData);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAsync(string serviceName, string id, bool incData)
        {
            return base.Channel.FindDocumentsByServiceNameKeyValueAsync(serviceName, id, incData);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAndDocTypeAsync(string docType, string serviceName, string id, bool incData)
        {
            return base.Channel.FindDocumentsByServiceNameKeyValueAndDocTypeAsync(docType, serviceName, id, incData);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValuePagerAsync(string serviceName, string id, int page, int pageSize, string sortBy, string sortDirection, bool incData)
        {
            return base.Channel.FindDocumentsByServiceNameKeyValuePagerAsync(serviceName, id, page, pageSize, sortBy, sortDirection, incData);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SkillsDocumentsService.SkillsDocument>> FindDocumentsByServiceNameKeyValueAndDocTypePagerAsync(string docType, string serviceName, string id, int page, int pageSize, string sortBy, string sortDirection, bool incData)
        {
            return base.Channel.FindDocumentsByServiceNameKeyValueAndDocTypePagerAsync(docType, serviceName, id, page, pageSize, sortBy, sortDirection, incData);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.FormatDocumentResponse> FormatDocumentMakeRequestAsync(long docId, string formatter, string requestedBy)
        {
            return base.Channel.FormatDocumentMakeRequestAsync(docId, formatter, requestedBy);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.FormatDocumentResponse> FormatDocumentPollStatusAsync(long docId, string formatter)
        {
            return base.Channel.FormatDocumentPollStatusAsync(docId, formatter);
        }
        
        public System.Threading.Tasks.Task<byte[]> FormatDocumentGetPayloadAsync(long docId, string formatter)
        {
            return base.Channel.FormatDocumentGetPayloadAsync(docId, formatter);
        }
        
        public System.Threading.Tasks.Task<string> GetSkillsDocumentKeyValueAsync(long docId, string keyName)
        {
            return base.Channel.GetSkillsDocumentKeyValueAsync(docId, keyName);
        }
        
        public System.Threading.Tasks.Task UpdateSkillsDocumentKeyValueAsync(long docId, string keyName, string keyValue, string updatedBy)
        {
            return base.Channel.UpdateSkillsDocumentKeyValueAsync(docId, keyName, keyValue, updatedBy);
        }
        
        public System.Threading.Tasks.Task<string> InsertDocumentTypeAsync(SkillsDocumentsService.SkillsDocumentType docType)
        {
            return base.Channel.InsertDocumentTypeAsync(docType);
        }
        
        public System.Threading.Tasks.Task DeleteDocumentTypeAsync(string docTypeText)
        {
            return base.Channel.DeleteDocumentTypeAsync(docTypeText);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDocumentTypeAsync(SkillsDocumentsService.SkillsDocumentType docType)
        {
            return base.Channel.UpdateDocumentTypeAsync(docType);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocumentType> GetDocumentTypeByNameAsync(string docTypeName)
        {
            return base.Channel.GetDocumentTypeByNameAsync(docTypeName);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.SkillsDocumentType> GetDocumentTypeByIdAsync(int docTypeId)
        {
            return base.Channel.GetDocumentTypeByIdAsync(docTypeId);
        }
        
        public System.Threading.Tasks.Task<SkillsDocumentsService.Question> GetSkillsHealthCheckQuestionsAsync(SkillsDocumentsService.AssessmentType assessmentType, int questionNumber, SkillsDocumentsService.Level level, SkillsDocumentsService.Accessibility accessibility)
        {
            return base.Channel.GetSkillsHealthCheckQuestionsAsync(assessmentType, questionNumber, level, accessibility);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basic))
            {
                return new System.ServiceModel.EndpointAddress("http://cds-dev-01-skillscentral.cloudapp.net/SkillsService.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SkillsCentralServiceClient.GetBindingForEndpoint(EndpointConfiguration.basic);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SkillsCentralServiceClient.GetEndpointAddress(EndpointConfiguration.basic);
        }
        
        public enum EndpointConfiguration
        {
            
            basic,
        }
    }
}
